### 1. csv, xls을 웹주소와 로컬 파일로 각각 읽어서 데이터프레임 작성

In [39]:
import requests

url = "https://raw.githubusercontent.com/MyungKyuYi/AI-class/main/mobile.csv"
response = requests.get(url)

with open('mobile.csv', 'wb') as file:
    file.write(response.content)

# 저장된 파일을 pandas로 읽기
df = pd.read_csv('mobile.csv')
print(df.head())

   battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_

In [41]:
import pandas as pd

# raw 파일 URL 사용
url = "https://raw.githubusercontent.com/MyungKyuYi/AI-class/main/mobile.csv"
df = pd.read_csv(url)

# 데이터 확인
print(df.head())


   battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_

In [48]:
import requests
import pandas as pd

# GitHub 원시 URL
url = "https://raw.githubusercontent.com/MyungKyuYi/AI-class/main/combined_dataset-1.xlsx"

# 파일 다운로드
response = requests.get(url)
with open("combined_dataset-1.xlsx", "wb") as file:
    file.write(response.content)

# 로컬 파일을 pandas로 읽기
df = pd.read_excel("combined_dataset-1.xlsx")

# 데이터 확인
print(df.head())

   Num.  subject_ID Sex(M/F)  Age(year)  Height(cm)  Weight(kg)  \
0     1           2   Female         45         152          63   
1     1           2   Female         45         152          63   
2     1           2   Female         45         152          63   
3     2           3   Female         50         157          50   
4     2           3   Female         50         157          50   

   Systolic Blood Pressure(mmHg)  Diastolic Blood Pressure(mmHg)  \
0                            161                              89   
1                            161                              89   
2                            161                              89   
3                            160                              93   
4                            160                              93   

   Heart Rate(b/m)  BMI(kg/m^2)  ...  2091  2092  2093  2094  2095  2096  \
0               97    27.268006  ...  1766  1766  1766  1833  1833  1827   
1               97    27.268006  ...

In [47]:
import pandas as pd

# raw 파일 URL 사용
url = "https://raw.githubusercontent.com/MyungKyuYi/AI-class/main/combined_dataset-1.xlsx"
df = pd.read_excel(url)

# 데이터 확인
print(df.head())


   Num.  subject_ID Sex(M/F)  Age(year)  Height(cm)  Weight(kg)  \
0     1           2   Female         45         152          63   
1     1           2   Female         45         152          63   
2     1           2   Female         45         152          63   
3     2           3   Female         50         157          50   
4     2           3   Female         50         157          50   

   Systolic Blood Pressure(mmHg)  Diastolic Blood Pressure(mmHg)  \
0                            161                              89   
1                            161                              89   
2                            161                              89   
3                            160                              93   
4                            160                              93   

   Heart Rate(b/m)  BMI(kg/m^2)  ...  2091  2092  2093  2094  2095  2096  \
0               97    27.268006  ...  1766  1766  1766  1833  1833  1827   
1               97    27.268006  ...

### 

In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 1. CSV 파일 불러오기
df = pd.read_csv("iris.csv")

# 2. 데이터 분할 (특성 & 타겟)
X = df.iloc[:, :-1]  # 마지막 열(target) 제외한 모든 열이 특성 데이터
y = df.iloc[:, -1]   # 마지막 열(target)만 가져오기

# 3. 데이터 분할 (훈련 80%, 테스트 20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 4. 데이터 표준화 (KNN은 거리 기반이므로 스케일링 필수)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 5. 최적의 K 값 찾기
k_values = range(1, 21)  # 1부터 20까지 K 값 테스트
accuracies = []

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    accuracies.append(acc)

# 6. 최적 K 값 출력
best_k = k_values[np.argmax(accuracies)]
best_accuracy = max(accuracies)
print(f"최적의 K 값: {best_k}, 정확도: {best_accuracy:.2f}")

# 7. 최적 K 값으로 최종 모델 학습
knn = KNeighborsClassifier(n_neighbors=best_k)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

# 8. 예측 및 평가
accuracy = accuracy_score(y_test, y_pred)
print(f"최종 모델 (K={best_k}) 정확도: {accuracy:.2f}")

# 9. 결과 출력 (처음 5개 샘플 비교)
for i in range(5):
    print(f"실제값: {y_test.iloc[i]}, 예측값: {y_pred[i]}")


최적의 K 값: 1, 정확도: 1.00
최종 모델 (K=1) 정확도: 1.00
실제값: Iris-versicolor, 예측값: Iris-versicolor
실제값: Iris-setosa, 예측값: Iris-setosa
실제값: Iris-virginica, 예측값: Iris-virginica
실제값: Iris-versicolor, 예측값: Iris-versicolor
실제값: Iris-versicolor, 예측값: Iris-versicolor


In [14]:
# SVM (서포트 벡터 머신 분류 모델)
from sklearn.svm import SVC

svm_model = SVC()
svm_model.fit(X_train, y_train)
svm_pred = svm_model.predict(X_test)
svm_acc = accuracy_score(y_test, svm_pred)
print(f'SVM Accuracy: {svm_acc:.4f}\n')
print(classification_report(y_test, svm_pred), '\n')
print(confusion_matrix(y_test, svm_pred))
for i in range(20):
    print(f"실제값: {y_test.iloc[i]}, 예측값: {svm_pred[i]}")

SVM Accuracy: 1.0000

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30
 

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
실제값: Iris-versicolor, 예측값: Iris-versicolor
실제값: Iris-setosa, 예측값: Iris-setosa
실제값: Iris-virginica, 예측값: Iris-virginica
실제값: Iris-versicolor, 예측값: Iris-versicolor
실제값: Iris-versicolor, 예측값: Iris-versicolor
실제값: Iris-setosa, 예측값: Iris-setosa
실제값: Iris-versicolor, 예측값: Iris-versicolor
실제값: Iris-virginica, 예측값: Iris-virginica
실제값: Iris-versicolor, 예측값: Iris-versicolor
실제값: Iris-versicolor, 예측값: Iris-versicolor
실제값: Iris-virginica, 예측값: Iris-virginica
실제값: Iris-setosa, 예측값: Iris-setosa
실제값: Iris-setosa, 예측값: Iris-setosa
실제값: Iris-setosa