<a href="https://colab.research.google.com/github/Tea-Yeon-Kim/AI-Class/blob/main/week3/week3_car_evaluation2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
import seaborn as sns
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras

# LabelEncoder 객체 생성
label_encoder = LabelEncoder()

df = pd.read_csv("/content/drive/MyDrive/AI_Class/car_evaluation.csv", header = None)
df

0      1      2     3      4     5      6
0     vhigh  vhigh      2     2  small   low  unacc
1     vhigh  vhigh      2     2  small   med  unacc
2     vhigh  vhigh      2     2  small  high  unacc
3     vhigh  vhigh      2     2    med   low  unacc
4     vhigh  vhigh      2     2    med   med  unacc
...     ...    ...    ...   ...    ...   ...    ...
1723    low    low  5more  more    med   med   good
1724    low    low  5more  more    med  high  vgood
1725    low    low  5more  more    big   low  unacc
1726    low    low  5more  more    big   med   good
1727    low    low  5more  more    big  high  vgood

[1728 rows x 7 columns]

In [ ]:
df.columns = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']

In [ ]:
df.columns

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class'], dtype='object')

In [ ]:
# 결측치 확인
missing_values = df.isnull().sum()

print("\n결측치 개수:")
print(missing_values)


결측치 개수:
buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
class       0
dtype: int64


In [ ]:
# 결측치 제거
df = df.dropna()
missing_values = df.isnull().sum()

print("\n결측치 개수:")
print(missing_values)


결측치 개수:
buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
class       0
dtype: int64


In [ ]:
# 모든 컬럼에 대해 LabelEncoder를 적용
for column in df.columns:
    if df[column].dtype == 'object':  # 범주형 컬럼만 변환
        df[column] = label_encoder.fit_transform(df[column])

df.head()

buying  maint  doors  persons  lug_boot  safety  class
0       3      3      0        0         2       1      2
1       3      3      0        0         2       2      2
2       3      3      0        0         2       0      2
3       3      3      0        0         1       1      2
4       3      3      0        0         1       2      2

In [ ]:
# 'class' 열의 개수 확인 (레이블 확인)
class_count = df['class'].value_counts()

# 결과 출력
print("class 개수:")
print(class_count)

class 개수:
class
2    1210
0     384
1      69
3      65
Name: count, dtype: int64


In [ ]:
# X와 y 나누기
X = df.drop('class', axis=1).values
y = df['class'].values

In [ ]:
X

array([[3, 3, 0, 0, 2, 1],
       [3, 3, 0, 0, 2, 2],
       [3, 3, 0, 0, 2, 0],
       ...,
       [1, 1, 3, 2, 0, 1],
       [1, 1, 3, 2, 0, 2],
       [1, 1, 3, 2, 0, 0]])

In [ ]:
y

array([2, 2, 2, ..., 2, 1, 3])

In [ ]:
# 데이터 정규화 (평균 0, 표준편차 1로 변환)
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [ ]:
# 데이터를 훈련 세트와 테스트 세트로 분할 (80% 훈련, 20% 테스트)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1382, 6), (346, 6), (1382,), (346,))

In [ ]:
# Decision Tree (의사결정나무 분류 모델)
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier()
dt_model.fit(X_train, y_train)  # 모델 학습

dt_pred = dt_model.predict(X_test)  # 테스트 데이터 예측
dt_acc = accuracy_score(y_test, dt_pred)  # 정확도 평가
print(f'Decision Tree Accuracy: {dt_acc:.4f}\n')
print(classification_report(y_test, dt_pred), '\n')
print(confusion_matrix(y_test, dt_pred))

Decision Tree Accuracy: 0.9884

              precision    recall  f1-score   support

           0       0.96      0.99      0.97        77
           1       0.93      1.00      0.97        14
           2       1.00      0.99      1.00       242
           3       1.00      0.92      0.96        13

    accuracy                           0.99       346
   macro avg       0.97      0.98      0.97       346
weighted avg       0.99      0.99      0.99       346
 

[[ 76   1   0   0]
 [  0  14   0   0]
 [  2   0 240   0]
 [  1   0   0  12]]


In [ ]:
# Logistic Regression (로지스틱 회귀 분류 모델)
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(max_iter=200)
lr_model.fit(X_train, y_train)

lr_pred = lr_model.predict(X_test)
lr_acc = accuracy_score(y_test, lr_pred)
print(f'Logistic Regression Accuracy: {lr_acc:.4f}\n')
print(classification_report(y_test, lr_pred, zero_division=1), '\n')
print(confusion_matrix(y_test, lr_pred))

Logistic Regression Accuracy: 0.6879

              precision    recall  f1-score   support

           0       0.25      0.06      0.10        77
           1       1.00      0.00      0.00        14
           2       0.73      0.95      0.83       242
           3       0.18      0.15      0.17        13

    accuracy                           0.69       346
   macro avg       0.54      0.29      0.27       346
weighted avg       0.62      0.69      0.61       346
 

[[  5   0  63   9]
 [  1   0  13   0]
 [ 11   0 231   0]
 [  3   0   8   2]]


In [ ]:
# SVM (서포트 벡터 머신 분류 모델)
from sklearn.svm import SVC

svm_model = SVC()
svm_model.fit(X_train, y_train)

svm_pred = svm_model.predict(X_test)
svm_acc = accuracy_score(y_test, svm_pred)
print(f'SVM Accuracy: {svm_acc:.4f}\n')
print(classification_report(y_test, svm_pred), '\n')
print(confusion_matrix(y_test, svm_pred))

SVM Accuracy: 0.9046

              precision    recall  f1-score   support

           0       0.73      0.91      0.81        77
           1       1.00      0.14      0.25        14
           2       0.97      0.95      0.96       242
           3       0.91      0.77      0.83        13

    accuracy                           0.90       346
   macro avg       0.90      0.69      0.71       346
weighted avg       0.92      0.90      0.90       346
 

[[ 70   0   6   1]
 [ 12   2   0   0]
 [ 11   0 231   0]
 [  3   0   0  10]]


In [ ]:
# Random Forest (랜덤 포레스트 분류 모델)
from sklearn.ensemble import RandomForestClassifier

# 모델 학습
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# 예측 및 평가
rf_pred = rf_model.predict(X_test)
rf_acc = accuracy_score(y_test, rf_pred)
print(f'Random Forest Accuracy: {rf_acc:.4f}\n')
print(classification_report(y_test, rf_pred), '\n')
print(confusion_matrix(y_test, rf_pred))

Random Forest Accuracy: 0.9913

              precision    recall  f1-score   support

           0       0.99      0.97      0.98        77
           1       0.93      1.00      0.97        14
           2       1.00      1.00      1.00       242
           3       1.00      0.92      0.96        13

    accuracy                           0.99       346
   macro avg       0.98      0.97      0.98       346
weighted avg       0.99      0.99      0.99       346
 

[[ 75   1   1   0]
 [  0  14   0   0]
 [  0   0 242   0]
 [  1   0   0  12]]
